window.ARMON_STORE = {
  freeShippingMin: 2499,
  standardShipping: 99,
  expressShipping: 149,
  products: [
    {
      id: "set-alo-plata",
      name: "Set Alo Plata",
      price: 2190,
      category: "Fit",
      image: "./IMG-20260628-WA0036.jpg",
      accentColor: "#aeb2b8",
      alt: "Set Alo Plata en maniquí",
      tagline: "Activewear · Silueta técnica",
      description:
        "Set completo Alo Yoga en acabado plata con chaqueta crop y legging de compresión media. Tela four-way stretch, secado rápido y caída esculpida para studio o street.",
      sizes: ["XS", "S", "M", "L"],
      material: "Nylon-elastano premium · Piping contrastante",
      care: "Lavado en frío · No blanqueador · Secado a la sombra",
      delivery: "Entrega 2–4 días hábiles CDMX · 3–6 días resto del país",
    },
    {
      id: "set-alo-carbon",
      name: "Set Alo Carbón",
      price: 2090,
      category: "Fit",
      image: "./IMG-20260628-WA0026.jpg",
      accentColor: "#5a5856",
      alt: "Set Alo Carbón con piping",
      tagline: "Activewear · Línea nocturna",
      description:
        "Conjunto Alo en tono carbón con ribetes claros. Top corto estructurado y legging de alta compresión. Ideal para entrenamiento o look athleisure elevado.",
      sizes: ["XS", "S", "M", "L"],
      material: "Mezcla técnica Alo · Costuras planas",
      care: "Lavado delicado · Secado natural",
      delivery: "Entrega 2–4 días hábiles CDMX · 3–6 días resto del país",
    },
    {
      id: "set-alo-studio",
      name: "Set Alo Studio",
      price: 1990,
      category: "Fit",
      image: "./IMG-20260628-WA0023.jpg",
      accentColor: "#c4c8cc",
      alt: "Set Alo Studio plata con chaqueta negra",
      tagline: "Activewear · Edición studio",
      description:
        "Set en plata con chaqueta negra superpuesta. Legging sculpt y top de soporte medio. Curaduría pensada para transición gym-to-coffee.",
      sizes: ["XS", "S", "M", "L"],
      material: "Jersey técnico · Paneles de malla localizada",
      care: "Lavado en frío · Planchar tibio invertido",
      delivery: "Entrega 2–4 días hábiles CDMX · 3–6 días resto del país",
    },
    {
      id: "chaqueta-carbon",
      name: "Chaqueta Crop Carbón",
      price: 2490,
      category: "Fit",
      image: "./IMG-20260628-WA0028.jpg",
      accentColor: "#48464a",
      alt: "Chaqueta crop carbón Alo",
      tagline: "Outerwear · Crop estructurado",
      description:
        "Chaqueta crop Alo en carbón con cierre frontal y cuello alto. Capa exterior ligera con acabado soft-touch y presencia de showroom.",
      sizes: ["XS", "S", "M", "L"],
      material: "Poliéster técnico · Forro mesh",
      care: "Lavado a mano o ciclo delicado",
      delivery: "Entrega 2–4 días hábiles CDMX · 3–6 días resto del país",
    },
    {
      id: "chaqueta-oliva",
      name: "Chaqueta Oliva Alo",
      price: 2390,
      category: "Fit",
      image: "./IMG-20260628-WA0030.jpg",
      accentColor: "#4f4e38",
      alt: "Chaqueta oliva camo Alo",
      tagline: "Outerwear · Camo oliva",
      description:
        "Chaqueta Alo en camo oliva con corte cropped y cierre completo. Pieza statement para capas sobre set neutro o legging negro.",
      sizes: ["XS", "S", "M", "L"],
      material: "Nylon ripstop suave · Cierre YKK",
      care: "Lavado en frío · No secadora",
      delivery: "Entrega 2–4 días hábiles CDMX · 3–6 días resto del país",
    },
    {
      id: "hoodie-camo-gris",
      name: "Hoodie Camo Gris",
      price: 2590,
      category: "Fit",
      image: "./IMG-20260628-WA0031.jpg",
      accentColor: "#7a7976",
      alt: "Hoodie camo gris Alo con leggings",
      tagline: "Layering · Camo urbano",
      description:
        "Hoodie camo gris Alo de fit relajado con capucha estructurada. Combínalo con legging técnico para un uniforme premium off-duty.",
      sizes: ["XS", "S", "M", "L", "XL"],
      material: "Algodón-orgánico mezcla · Felpa interior",
      care: "Lavado en frío · Secado bajo",
      delivery: "Entrega 2–4 días hábiles CDMX · 3–6 días resto del país",
    },
    {
      id: "set-nike-arena",
      name: "Set Nike Zip Arena",
      price: 2290,
      category: "Fit",
      image: "./IMG-20260629-WA0026.jpg",
      accentColor: "#b8a88a",
      alt: "Set Nike arena con chaqueta zip y legging",
      tagline: "Nike · Zip-up sculpt",
      description:
        "Conjunto Nike en tono arena: chaqueta corta con cierre, cuello alto y legging de cintura alta. Tejido elástico con swoosh discreto y silueta contorneada.",
      sizes: ["XS", "S", "M", "L"],
      material: "Poliéster-elastano Dri-FIT feel",
      care: "Lavado en frío · No suavizante",
      delivery: "Entrega 2–4 días hábiles CDMX · 3–6 días resto del país",
    },
    {
      id: "set-nike-negro",
      name: "Set Nike Zip Negro",
      price: 2190,
      category: "Fit",
      image: "./IMG-20260629-WA0027.jpg",
      accentColor: "#2a2a2a",
      alt: "Set Nike negro con chaqueta zip y biker",
      tagline: "Nike · All black edit",
      description:
        "Set Nike negro con chaqueta zip corta y biker de tiro alto. Look monocromo con líneas verticales que alargan la silueta. Perfecto para training o salida casual.",
      sizes: ["XS", "S", "M", "L"],
      material: "Jersey técnico · Costuras contorneadas",
      care: "Lavado en frío · Secado a la sombra",
      delivery: "Entrega 2–4 días hábiles CDMX · 3–6 días resto del país",
    },
    {
      id: "set-polo-navy",
      name: "Set Polo Wide Navy",
      price: 2490,
      category: "Fit",
      image: "./IMG-20260630-WA0006.jpg",
      accentColor: "#1a2744",
      alt: "Set polo navy con pantalón wide leg",
      tagline: "Sport chic · Wide leg",
      description:
        "Conjunto polo navy con cuello contrastante blanco y pantalón wide leg con franja lateral. Estética country club elevada con caída relajada premium.",
      sizes: ["XS", "S", "M", "L"],
      material: "Piqué-algodón mezcla · Pretina elástica con cordón",
      care: "Lavado en frío · Planchar del revés",
      delivery: "Entrega 2–4 días hábiles CDMX · 3–6 días resto del país",
    },
    {
      id: "set-polo-rojo",
      name: "Set Polo Wide Rojo",
      price: 2390,
      category: "Fit",
      image: "./IMG-20260630-WA0002.jpg",
      accentColor: "#c41e3a",
      alt: "Set polo blanco y pantalón rojo wide leg",
      tagline: "Sport chic · Contraste bold",
      description:
        "Playera polo blanca con cuello rojo y pantalón wide leg fucsia con franja blanca. Set statement para brunch, viaje o street style con actitud.",
      sizes: ["XS", "S", "M", "L"],
      material: "Algodón-poliéster premium · Bordado logo",
      care: "Lavado en frío · No blanqueador",
      delivery: "Entrega 2–4 días hábiles CDMX · 3–6 días resto del país",
    },
    {
      id: "corse-negro",
      name: "Corsé Negro Mesh",
      price: 1390,
      category: "Casual",
      image: "./IMG-20260628-WA0021.jpg",
      accentColor: "#1a1420",
      alt: "Corsé negro mesh con jeans",
      tagline: "ALPER · Mesh nocturno",
      description:
        "Corsé negro con panel mesh y estructura interna flexible. Cierra la cintura sin perder movimiento. Ideal con denim recto o falda midi.",
      sizes: ["XS", "S", "M", "L"],
      material: "Poliéster mesh · Ballenas flexibles",
      care: "Lavado a mano · Secado plano",
      delivery: "Entrega 2–4 días hábiles CDMX · 3–6 días resto del país",
    },
    {
      id: "corse-rojo-alper",
      name: "Corsé Rojo ALPER",
      price: 1590,
      category: "Casual",
      image: "./IMG-20260628-WA0032.jpg",
      accentColor: "#b8143f",
      alt: "Corsé rojo ALPER con jeans",
      tagline: "ALPER · Statement red",
      description:
        "Corsé rojo intenso ALPER con broches frontales y corte corazón. Pieza protagonista para salida nocturna o date night con jeans o maxi satin.",
      sizes: ["XS", "S", "M", "L"],
      material: "Satín estructurado · Cierre frontal",
      care: "Lavado a mano · Planchado tibio",
      delivery: "Entrega 2–4 días hábiles CDMX · 3–6 días resto del país",
    },
    {
      id: "corse-bronce",
      name: "Corsé Bronce Estructurado",
      price: 1490,
      category: "Casual",
      image: "./IMG-20260628-WA0035.jpg",
      accentColor: "#96704e",
      alt: "Corsé bronce estructurado con jeans",
      tagline: "ALPER · Bronce glow",
      description:
        "Corsé bronce con acabado satinado y silueta hourglass. Tono cálido que eleva denim azul o negro. Curaduría going-out sin exceso.",
      sizes: ["XS", "S", "M", "L"],
      material: "Microfibra satinada · Ojales reforzados",
      care: "Lavado a mano · No retorcer",
      delivery: "Entrega 2–4 días hábiles CDMX · 3–6 días resto del país",
    },
    {
      id: "conjunto-denim-indigo",
      name: "Conjunto Denim ALPER Índigo",
      price: 1890,
      category: "Casual",
      image: "./IMG-20260629-WA0018.jpg",
      accentColor: "#3d4f6a",
      alt: "Chaleco denim índigo con jeans flare ALPER",
      tagline: "ALPER · Denim tailoring",
      description:
        "Chaleco denim índigo sin mangas con solapa, botones dorados y cinturón con hebilla floral incluido. Incluye jeans flare a juego. Look completo de pasarela boutique.",
      sizes: ["XS", "S", "M", "L"],
      material: "Denim algodón 98% · Herrajes dorados",
      care: "Lavado en frío del revés · Secado a la sombra",
      delivery: "Entrega 2–4 días hábiles CDMX · 3–6 días resto del país",
    },
    {
      id: "conjunto-denim-claro",
      name: "Conjunto Denim ALPER Claro",
      price: 1790,
      category: "Casual",
      image: "./IMG-20260629-WA0019.jpg",
      accentColor: "#8aa0b8",
      alt: "Chaleco denim claro con falda café ALPER",
      tagline: "ALPER · Light wash edit",
      description:
        "Chaleco denim lavado claro con cinturón floral a juego y falda mini café de tiro alto. Contraste sofisticado para salida de día o pre-cena.",
      sizes: ["XS", "S", "M", "L"],
      material: "Denim ligero · Falda mezcla viscosa",
      care: "Lavado en frío · Planchar tibio",
      delivery: "Entrega 2–4 días hábiles CDMX · 3–6 días resto del país",
    },
    {
      id: "chaleco-denim-indigo",
      name: "Chaleco Denim Hebilla Floral",
      price: 1490,
      category: "Casual",
      image: "./IMG-20260629-WA0021.jpg",
      accentColor: "#44556e",
      alt: "Chaleco denim índigo con hebilla floral dorada",
      tagline: "ALPER · Pieza hero",
      description:
        "Chaleco denim estructurado con solapa, bolsillos flap y hebilla floral dorada desmontable. Viste sobre caminho, falda o vestido slip.",
      sizes: ["XS", "S", "M", "L"],
      material: "Denim medio · Cierre botón dorado",
      care: "Lavado en frío del revés",
      delivery: "Entrega 2–4 días hábiles CDMX · 3–6 días resto del país",
    },
    {
      id: "chaleco-denim-claro",
      name: "Chaleco Denim Claro",
      price: 1390,
      category: "Casual",
      image: "./IMG-20260629-WA0023.jpg",
      accentColor: "#9eb0c4",
      alt: "Chaleco denim claro con hebilla floral",
      tagline: "ALPER · Wash claro",
      description:
        "Chaleco denim lavado claro con botones dorados y cinturón a juego. Silueta entallada con ligero peplum. Pieza versátil para capas editorial.",
      sizes: ["XS", "S", "M", "L"],
      material: "Denim suave · Herraje dorado",
      care: "Lavado delicado · No secadora",
      delivery: "Entrega 2–4 días hábiles CDMX · 3–6 días resto del país",
    },
    {
      id: "vestido-galaxia",
      name: "Vestido Noche Galaxia",
      price: 3290,
      category: "Casual",
      image: "./IMG-20260630-WA0004.jpg",
      accentColor: "#1a1a2e",
      alt: "Vestido largo negro con strass galaxia",
      tagline: "Noche · Full strass",
      description:
        "Vestido largo bodycon cubierto de micro strass negro-plata con drapeado lateral y escote redondo. Entrada de gala, cena o evento donde quieras brillar sin gritar.",
      sizes: ["XS", "S", "M", "L"],
      material: "Malla elastizada · Aplicación strass completa",
      care: "Lavado a mano · Guardar colgado",
      delivery: "Entrega 2–4 días hábiles CDMX · 3–6 días resto del país",
    },
  ],
  videos: [
    {
      id: "reel-nike",
      src: "./VID-20260629-WA0028.mp4",
      poster: "./IMG-20260629-WA0027.jpg",
      label: "Nike Zip Edit",
      category: "Fit",
    },
    {
      id: "reel-denim",
      src: "./VID-20260629-WA0029.mp4",
      poster: "./IMG-20260629-WA0018.jpg",
      label: "Denim ALPER",
      category: "Casual",
    },
    {
      id: "reel-gala",
      src: "./VID-20260630-WA0007.mp4",
      poster: "./IMG-20260630-WA0004.jpg",
      label: "Noche Galaxia",
      category: "Casual",
    },
    {
      id: "reel-polo",
      src: "./VID-20260630-WA0008.mp4",
      poster: "./IMG-20260630-WA0002.jpg",
      label: "Polo Wide Leg",
      category: "Fit",
    },
  ],
};
